#Displays a welcome message. Don't delete the apostrophes
loginmessage: '&aWelcome to the server! &bEnjoy your stay.'
#Rules displayed when summmoned by a command
rules:
- Do not grief
- Respect all players
- Do not use cheats to gain an advantage